spring.application.name=Project-Task-Service
server.port=${SERVER_PORT:8084}

# Datasource (PostgreSQL - own isolated DB for this service)
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/project_task_db}
spring.datasource.username=postgres
spring.datasource.password=Novemba@42

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Kafka - Redpanda Cloud
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:d8vr583l9b9vq71tb8gg.any.eu-central-1.mpx.prd.cloud.redpanda.com:9092}
spring.kafka.security.protocol=SASL_SSL
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="slasher" password="TT4242@mtskr";
spring.kafka.consumer.group-id=project-task-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# JWT - must use the same secret as Auth-Security-Service so tokens issued there validate here
app.jwt.secret=${JWT_SECRET:dGhpcy1pcy1hLWRldi1vbmx5LXNlY3JldC1rZXktY2hhbmdlLW1lLWluLXByb2R1Y3Rpb24h}
