package com.ced.Auth.Security.Service.domain;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILURE,
    ACCOUNT_LOCKED,
    ACCOUNT_UNLOCKED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_COMPLETED,
    MFA_ENABLED,
    MFA_DISABLED,
    MFA_VERIFIED,
    SETTINGS_UPDATED,
    MAINTENANCE_MODE_TOGGLED,
    BACKUP_TRIGGERED,
    BACKUP_SUCCEEDED,
    BACKUP_FAILED
}
